grpc:
  server:
    port: 8095
    max-inbound-message-size: 50MB
    max-outbound-message-size: 50MB
    flow-control-window: 10485760
    permit-keep-alive-without-calls: true
    handshake-timeout: 30000
    keep-alive-time: 30s
    keep-alive-timeout: 10s

spring:
  application:
    name: rococo-painting
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: root
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rococo-painting
    locations: classpath:db/migration/rococo-painting
  jpa:
    properties:
      javax.persistence.validation.mode: CALLBACK
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.springframework.web: INFO
    io.grpc: DEBUG
    io.grpc.netty: DEBUG
    io.netty: DEBUG
    guru.qa.rococo: DEBUG
    org.springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:mysql://rococo-all-db:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'
  jpa:
    hibernate:
      ddl-auto: validate
---